// THIS IS FOR GETTING MEN DATA TO SEARCH RESULT
export const GET_MEN_CLOTHES_DATA_REQUEST = "GET_MEN_CLOTHES_DATA_REQUEST";
export const GET_MEN_CLOTHES_DATA_SUCCESS = "GET_MEN_CLOTHES_DATA_SUCCESS";
export const GET_MEN_CLOTHES_DATA_FAILURE = "GET_MEN_CLOTHES_DATA_FAILURE";

// THIS IS FOR GETTING WOMEN DATA TO SEARCH RESULT
export const GET_WOMEN_CLOTHES_DATA_REQUEST = "GET_WOMEN_CLOTHES_DATA_REQUEST";
export const GET_WOMEN_CLOTHES_DATA_SUCCESS = "GET_WOMEN_CLOTHES_DATA_SUCCESS";
export const GET_WOMEN_CLOTHES_DATA_FAILURE = "GET_WOMEN_CLOTHES_DATA_FAILURE";

// THIS IS FOR GETTING KIDS DATA TO SEARCH RESULT
export const GET_KIDS_CLOTHES_DATA_REQUEST = "GET_KIDS_CLOTHES_DATA_REQUEST";
export const GET_KIDS_CLOTHES_DATA_SUCCESS = "GET_KIDS_CLOTHES_DATA_SUCCESS";
export const GET_KIDS_CLOTHES_DATA_FAILURE = "GET_KIDS_CLOTHES_DATA_FAILURE";
